const {PAGES} = require("./pages");
let PHASE = {
  CDA: {
    INITIAL: [
      PAGES.HOME,
      PAGES.BASIC_INFORMATION,
      PAGES.PEP,
      PAGES.ACCOUNT,
    ],
    FINAL: [
      PAGES.CARD,
      PAGES.CARD_CONFIRM_DELIVERY_ADDRESS_POPUP,
      PAGES.DECLARING,
      PAGES.SIGNATURE,
      PAGES.TIPS,
    ],
    NO_CLIENT: [
      PAGES.PERSONAL_INFORMATION,
      PAGES.ECONOMIC_ACTIVITY,
      PAGES.CONTACT_INFORMATION,
      PAGES.FOREIGN_INFORMATION,
      PAGES.FINANCIAL_INFORMATION,
    ],
  },
  CDT: {
    INITIAL: [
      PAGES.CDT_HOME,
      PAGES.CDT_BASIC_INFORMATION,
      PAGES.PEP,
      PAGES.CDT_CONFIG,
    ],
    FINAL: [
      PAGES.CDT_ACCOUNT_CONFIG,
      PAGES.DECLARING,
      PAGES.CDT_SIGNATURE,
    ],
    SUMMARY: [
      PAGES.TIPS
    ],
    NO_CLIENT: [
      PAGES.CDT_PERSONAL_INFORMATION,
      PAGES.ECONOMIC_ACTIVITY,
      PAGES.CONTACT_INFORMATION,
      PAGES.FOREIGN_INFORMATION,
      PAGES.FINANCIAL_INFORMATION,
    ],
  },
  INSURANCE: [
    PAGES.INSURANCE,
  ],
  ENROLLMENT: [
    PAGES.ENROLLMENT
  ],
  NO_CLIENT: [
    PAGES.PERSONAL_INFORMATION,
    PAGES.ECONOMIC_ACTIVITY,
    PAGES.CONTACT_INFORMATION,
    PAGES.FOREIGN_INFORMATION,
  ],
  IDENTIFICATION: [
    PAGES.OTP,
  ],
  CUSTOMER: {},
  UPDATED: {},
  NO_UPDATED: {},
}

module.exports = {
  PHASE
};
