# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Running Cypress Tests

on:
  release:
    types: [created]

jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run cypress:run:spec
        env:
          environment: 'dev'
          spec: 'cypress/integration/test/flows/CDT/3.Cliente_PEP.js'

  publish-results:
    if: always()
    needs: running-test
    runs-on: ubuntu-latest
    steps:
      - name: Commit screenshots
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Screenshots
